### ISSUE TITLE
Temperature sensor

### ISSUE THREAD

**Issue by Dirbaio** [akiles/nrf-softdevice#13]
Should be easy, just calling `sd_temp_get`.

Maybe check if there's a HAL trait out there and implement that.

**Comment by jacobrosenthal** [comment]
There isnt a eh trait that Im aware of. 

The nrf hals do this
https://github.com/nrf-rs/nrf-hal/blob/4692919084613fb5f697021897de697b3f8fe43f/nrf-hal-common/src/temp.rs

I presume its wrapped because of the blocking nature
https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.s132.api.v3.0.0%2Fgroup___n_r_f___s_o_c___f_u_n_c_t_i_o_n_s.html&anchor=gade0ea69f513ff1feab2c4f6e1c393313
"It takes around 50us from call to return"
